% Generated by Friedman: do not edit by hand

\name{PeirceData}
\alias{PeirceData}
\alias{makePeirceData}
\title{PeirceData.}
\usage{
  makePeirceData(desc, data, colnames.old, colnames.new, target.features)
}
\arguments{
  \item{desc}{[\code{PeirceDataDescription}]\cr
    Data set description.}
  
  \item{data}{[\code{data.frame}]\cr
    The data set.}
  
  \item{colnames.old}{[\code{character}]\cr
    Names of the features that were uploaded to the server.}
  
  \item{colnames.new}{[\code{character}]\cr
    Names of the features that are displayed.}
  
  \item{target.features}{[\code{character}]\cr
    Name of the target feature(s).}
}
\value{
  [\code{PeirceData}]
}
\description{
  An \code{PeirceData} consists of an \code{PeirceDataDescription}, a
  \code{data.frame} containing the data set, the old and new column names and,
  finally, the target features.
  
  The \code{\link{PeirceDataDescription}} provides information on the data set,
  like the ID, name, version, etc. To see a full list of all elements, please see the
  \href{https://github.com/openml/website/blob/master/openml_OS/views/pages/api_new/v1/xsd/openml.data.upload.xsd}{XSD}.
  
  The slot \code{colnames.old} contains the original names, i.e., the column names that were
  uploaded to the server, while \code{colnames.new} contains the names that you will see when
  working with the data in R.
  Most of the time, old and new column names are identical. Only if the original names are
  not valid, the new ones will differ.
  
  The slot \code{target.features} contains the column name(s) from the \code{data.frame}
  of the \code{PeirceData} that refer to the target feature(s).
}
\seealso{
  Other dataset related functions: \code{\link{PeirceDataDescription}},
  \code{\link{convertPeirceDataToMlr}},
  \code{\link{deleteOMLObject}},
  \code{\link{getPeirceData}},
  \code{\link{listPeirceDatas}},
  \code{\link{tagOMLObject}},
  \code{\link{uploadPeirceData}}
}